openapi: 3.0.0
info:
  title: Instagram User Post API's.
  description: In this Instagram feature these api's handle all the post related operations of Insta application.
  version: 1.1.3
servers:
  - url: http://localhost:5003
    description: local host uses the post number 5003.

components:
  schemas:
    user:
      type: object
      properties:
        username:
          type: string
          example: Crazy_Ninja
      required:  
          username 

paths:
  /signup:
    post:
      summary: This API is used to Register new user in Instagram.
      description: User can register by filling the entries.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
      responses:
        '201':
          description: Created.
        '406':
          description: Value not accepted.
        '500':
          description: Inernal server error.          
  /login:
    post:
      summary: This API is used to Logged In in Instagram.
      description: User can login by filling the entries.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
      responses:
        '200':
          description: Authorized.
        '401':
          description: Unauthorized Response.
        '500':
          description: Inernal server error.      
             

          